#!/bin/bash

#Este script ha de mantenerse en el directorio de git donde se requieren los dotfiles, de lo contrario cd $(dirname $(realpath $0)) fallará.
#Este script tiene rsync, git, coreutils, sudo y bash como dependencias


#Las rutas a los dotfiles han de especificarse en el array DOTFILES
declare -a DOTFILES=("$HOME/.zshrc" "$HOME/.config/kitty" "$HOME/.polybar" "$HOME/.config/bspwm" "$HOME/.config/sxhkd")
#--------------------------------------------------------------------------------------------



cd $(dirname $(realpath $0))
dec=$@


if [ -z "$dec" ]; then
	echo "\
	+--------------------------------+
	|       S · Sincronizar          |
	|       G · Subir a GITHUB       |
	|       E · Exportar al PC       |
	|                                |
	|  Cualquier otra tecla · Salir  |
	+--------------------------------+"
	read -p "Escoge: " dec
	dec=$(echo -$dec)
fi

case $dec in
-s|-S)
	sudo rsync -aAXv --delete ${DOTFILES[@]} .
	echo " "; ls -hNA --color=auto --group-directories-first; echo " "; git status; echo " "
	;;
-g|-G)
	git add --all ; git status; echo " "
	read -p "Commit? [Y/N]: " a; [[ $a =~ ^[Yy]$ ]] && git commit -m "`date`"
	read -p "Push? [Y/N]: " b; [[ $b =~ ^[Yy]$ ]] && git push origin master
		;;
-e|-E)
	[ -d "~/.config" ] && mkdir ~/.config
	for i in ${DOTFILES[@]}; do
		sudo rsync -aAXv --delete $(basename $i) $(dirname $i)
	done
	;;
*)
	echo "	Argumentos:
	-s · Sincronizar
	-g · Subir a GITHUB
	-e · Exportar al PC"
	;;
esac

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

Contact GitHub

