#!/bin/bash

echo "+----------------------+
|  1 · Sincronizar     |
|  2 · Subir a GITHUB  |
|  3 · Exportar al PC  |
+----------------------+"
read -p "Escoge: " dec 

cd $(dirname $(realpath $0))

if [ $dec -eq 1 ]
	then
		sudo rsync -aAXv --delete ~/.Xresources . 
		sudo rsync -aAXv --delete ~/.zshrc . 
		sudo rsync -aAXv --delete ~/.config/kitty/kitty.conf . 
		sudo rsync -aAXv --delete ~/.polybar . 
		sudo rsync -aAXv --delete ~/.config/bspwm/bspwmrc . 
		sudo rsync -aAXv --delete ~/.config/sxhkd/sxhkdrc . 
elif [ $dec -eq 2 ]
	then
		git add .Xresources
		git add .zshrc
		git add kitty.conf
		git add .polybar
		git add bspwmrc
		git add sxhkdrc
		git add sincronizar-dotfiles
		read -p "Commit? [Y/N]: " a
		if [[ $a =~ ^[Yy]$ ]]
			then
				git commit -m "Actualización automática"
		fi
		read -p "Push? [Y/N]: " b
		if [[ $b =~ ^[Yy]$ ]]
			then
				git push origin master
		fi
elif [ $dec -eq 3 ]
	then
		cp .Xresources ~/
		cp .zshrc ~/
		cp kitty.conf ~/.config/kitty/ #Comprobar si existe el directorio
		cp .polybar ~/
else 
		echo "Aprende a escribir." ;
fi


