#! /bin/sh

#AUTOSTART

killall -q polybar sxhkd

while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

sxhkd &

#killall -q polybar &

setxkbmap -layout es &

feh --bg-scale /home/xarly/Images/HyperBeast.jpg &

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

polybar -c ~/.polybar/.statusbar "sensores" &


#MONITORS

bspc monitor DVI-D-1 -d I II III IV V VI VII VIII IX X

#BSPWM C0NFIG

bspc config border_width        2
bspc config window_gap          7
bspc config top_padding		12
bspc config bottom_padding	0
bspc config right_padding	0
bspc config left_padding	0
bspc config single_monocle	false
bspc config click_to_focus	true
bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_by_distance	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus	true
bspc config pointer_modifier	mod4
bspc config pointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true

#### BSPWM coloring ####
bspc config normal_border_color		      "#721817"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#ff0000"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-1)
xdo above -t $(xdo id -n root) $(xdo id -n polybar)



